### ISSUE TITLE
Can't run example.js

### ISSUE THREAD

**Issue by haadcode** [noffle/pubsub-swarm#1]
Tried to run the example included, got the following error:

```
/Users/haad/code/pubsub-swarm/node_modules/secure-gossip/index.js:34
  this.interval = interval === -1 ? null : setInterval(this.gossip.bind(this), interval)
                                                                  ^

TypeError: Cannot read property 'bind' of undefined
    at new Gossip (/Users/haad/code/pubsub-swarm/node_modules/secure-gossip/index.js:34:67)
    at Gossip (/Users/haad/code/pubsub-swarm/node_modules/secure-gossip/index.js:17:43)
    at new Pubsub (/Users/haad/code/pubsub-swarm/index.js:19:17)
    at Pubsub (/Users/haad/code/pubsub-swarm/index.js:9:43)
    at Object.<anonymous> (/Users/haad/code/pubsub-swarm/example.js:3:13)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
```

Steps taken:

```
npm install
npm test
node example.js
```

Running Node.js v4.3.1 and npm v2.14.12

Any hints?

**Comment by hackergrrl** [comment]
Thanks for finding this, @haadcode! This was an upstream bug in [secure-gossip](https://github.com/noffle/secure-gossip) and is fixed as of `pubsub-swarm@0.1.2`.
